### ISSUE TITLE
Apps on the play store that implement this?

### ISSUE THREAD

**Issue by retorquere** [SimpleNexus/simplecallerid#11]
I'm looking patch something together to get caller ID for our corporate directory without having to import them all into my contacts list. Are there any apps that implement the methods from this repo on the play store?

**Comment by jacobmichaelis** [comment]
Yes there are apps that are on the app store that use this repo. Can I ask why you need to know if these methods are used on apps in the play store?

**Comment by retorquere** [comment]
If there's one I can feed my own contacts into, I wouldn't have to build & maintain my own. I've never used Kotlin and the last time I touched Java was 30 years ago.

**Comment by retorquere** [comment]
I just took it that the methods used in this repo are what makes such apps work; I've also seen apps that put up their own overlay instead of integrating with the dialer (such as NCID), and those were not very convenient.

**Comment by jacobmichaelis** [comment]
Ah, I see what you're saying. I think this repo is not really what you are looking for unless you are willing to write these methods into your existing app. This implementation makes it so that you don't have to save your corporate directory/in-app clients into your personal phone contacts, but can still see their contact info on the call screen when receiving a call from them.

**Comment by retorquere** [comment]
I don't have an app, I have a script that scrapes the corp directory; I can dump that in pretty much any format, but I need something that plugs that into the number recognition resolution machinery.

**Comment by retorquere** [comment]
Strangely enough, I tried a few CRM apps (albeit a while ago), and none seemed to integrate as well as this repo seems capable of.
