### ISSUE TITLE
How to get data from external API in Content Provider

### ISSUE THREAD

**Issue by ahmetbugraozcan** [SimpleNexus/simplecallerid#15]
Hello. I have an users API which contains users with name and phone values. So I don't want to get data from local database. Instead of I want to get data from a http request in Content provider. I am new in Android so I dont know how can I do it. When I research it, I found a component named sync adapter. Can I do what I want with that or do I use something else?

**Comment by jacobmichaelis** [comment]
I haven't done anything with this in a while, but theoretically it is possible to just do in the `query()` method of the content provide. I'm pretty sure everything is asynchronous so you could make the call there and wait for it. The thing you would run into is the time between the phone call coming in and the contact info displaying would be longer because it has to search over the network.

But also, I'm not really maintaining this repo anymore. Good luck figuring it out!
