### ISSUE TITLE
Some questions 

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [SimpleNexus/simplecallerid#7]
I've now tested on Pixel 2 Q.
Wanted to try some edge cases too, so figured out answers to them:
1. If the number is already stored on the address book, it shows what's there without using this app
2. If not, it shows what's on the app, including even in the recent calls screen on the Phone app.
3. If there are 2 apps that offer it (different package name and provider). It preferred the modified one. However, in the Phone app, in the recent-calls tab, it chose the one of the previous app. It happened even if there are no recent calls there. Weird.

But I still have a few questions :

1. How long does the app have before returning a result? This can be important for a real caller-id app, which needs to get the information from the server. 
2. Can all apps query this app for information, or just the default dialer ? 
3. If there are multiple apps that offer this, do all of them get queried, and the first one to return a result wins? If so, how come I saw the weird result? Is there a way to prioritize somehow? 
4. Is this whole method even legit? Do you know of any app that offers this service? If not, how come? Why isn't it common for caller-id apps? Maybe it's too public, giving away the information to other apps ?

**Comment by jacobmichaelis** [comment]
Thank you for posting this. I have a few thoughts:
- Edge case 3: Both the phone call page and recent-calls page request the data, so a phone call doesn't need to be made for caller ID to take effect.
- Q1: I believe in the case of a phone call, the app has until the user answers the phone to respond. Obviously that is not ideal though, and in the apps I've written the response is nearly instant. I would suggest caching user data from the server in the app so the data is readily available when calls come in.
- Q2: I believe all apps can query this information if they are set up for it. (The provider acts kind of like an Intent for data.) Any app that is permitted to ask for `android.content.ContactDirectory` should be able to gather this data.
- Q3: From what I've gathered from this, the app asks from all available data sources, but only listens until something is returned. Thus, which app gets displayed may appear random because it is based on who can answer first.
- Q4: This method is legit, the first app I saw this in was the LDS Tools app (written by some developers that attend my local Android Meetups). They guided me through implementing it on our app at SimpleNexus. Our customers all love this feature and complain incessantly that it is unavailable on Samsung (#6). I suppose you could say that this is sharing too much information, but with SharedPreferences you can turn the feature on and off for individual users, though I've found that most people want this rather than don't want this. Another reason retrieving this information dangerously is unlikely is that the querying app would need to know the phone number to get the name of the users.

If you have any more questions, or you find my statements to be wrong please let me know.

**Comment by farmerbb** [comment]
My assumption with why this method isn't more widely used is that there's basically no documentation whatsoever on how to do this, not even from Google.  Hence why we wanted to write some documentation and produce a sample repo ourselves.

**Comment by AndroidDeveloperLB** [comment]
Edge case #3 :
I still don't understand. Why would one being preferred in the call UI, and the other in the recent-calls screen? There is a single trigger in both cases. In one it's the phone call, and in the second it's manual, by just going to this screen...

1. What will happen if the user answers before the app gets to show the information? Can it still show it on the screen that is after the talk started?

2. So this can be risky for such apps, as others can mine the data quite easily. Isn't there a way to know which app has performed the query?

3. I see.

4. How did they find this information, of how it works and how to implement it? And why does it have issues on Samsung devices? Maybe with just its Phone app?

5. Which kind of information can the provider provide? Only name, or other things too, such as a photo? Can the photo be a Uri or a Bitmap, or something else?

**Comment by jacobmichaelis** [comment]
Edge Case 3: I don't know. As far as I can tell it is random, and Google doesn't offer any answers either.
Questions:
1. I haven't tried that, but I assume yes. A way to test this could be to have some sort of timeout to make the response take longer and see if it works. Let me know what you find if you beat me to it. Either way, it will show in the recent calls screen.
2. I don't know yet. I don't think so, but you should be able to debug the Provider and see what data is being passed in.
3. _No comment_
4. They actually figured it out from the AOSP and Google Dev Docs. I find that very impressive because the documentation on this is very bad and cryptic. 
5. More information on what can be sent can be found on the AOSP, however some people have posted their implementations on GitHub and [here is one I like to use for reference](https://github.com/sethsong90/CTS/blob/d2aefa0c9f4a0874708f4ff680fe646aafb948ac/hostsidetests/devicepolicy/app/ContactDirectoryProvider/src/com/android/cts/contactdirectoryprovider/DirectoryProvider.java). As you can see, you can send back pictures, which would be a great v2 tutorial to this app. It appears this person gets their photos in the form of a raw PNG.

**Comment by AndroidDeveloperLB** [comment]
I think you got the numbers wrong. I will trick Github for this :)

1+2.I actually think I can try those myself.

3.I see. Why do you think Samsung devices don't have it working? Is it because of their customized Phone app? Do you know if it's specific devices, and if it happens for other OEMs too?
I've tested now on Samsung Galaxy Note 8 with Android 8, and it seems it indeed doesn't work.

5.Can you please update the sample to include an image? It can be a static one of course, or auto-generated (solid color based on hashcode) based on the ID/phone-number of the person .

6.Suppose you have to download the image from the Internet. This means it could take some time. Is it possible to send the information twice? Once for basic info, and later including the photo?

7.This I can also check via emulators: Starting from which Android version is it available?

**Comment by jacobmichaelis** [comment]
Q3. Yes I believe it is because of their phone app, but it is also potentially because of their built in spam filtering service. Bixby will block calls and stuff, so some theorize that Bixby will block content providers.
Q5. I updated the project to have an image in it.
Q6. I have no idea. Feel free to try it out.
Q7. I don't know. I think it's possible this is available to any Android version because Content Providers are part of Android's original core library. My app though is only targeted at API21+ because that hits most devices.

**Comment by AndroidDeveloperLB** [comment]
3.I see. Is it possible to disable it? Did you notice this issue on other devices?
5.I think it crashes for me:

2019-11-05 21:12:13.449 16658-16809/com.example.simplecallerid E/AndroidRuntime: FATAL EXCEPTION: arch_disk_io_0
    Process: com.example.simplecallerid, PID: 16658
    java.lang.RuntimeException: Exception while computing database live data.
        at androidx.room.RoomTrackingLiveData$1.run(RoomTrackingLiveData.java:92)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.IllegalStateException: Room cannot verify the data integrity. Looks like you've changed schema but forgot to update the version number. You can simply fix this by increasing the version number.
        at androidx.room.RoomOpenHelper.checkIdentity(RoomOpenHelper.java:154)
        at androidx.room.RoomOpenHelper.onOpen(RoomOpenHelper.java:135)
        at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onOpen(FrameworkSQLiteOpenHelper.java:142)
        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:428)
        at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:317)
        at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:92)
        at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:53)
        at androidx.room.RoomDatabase.inTransaction(RoomDatabase.java:476)
        at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.java:281)
        at androidx.room.RoomDatabase.query(RoomDatabase.java:324)
        at androidx.room.util.DBUtil.query(DBUtil.java:83)
        at com.example.simplecallerid.db.UserDao_Impl$8.call(UserDao_Impl.java:218)
        at com.example.simplecallerid.db.UserDao_Impl$8.call(UserDao_Impl.java:215)
        at androidx.room.RoomTrackingLiveData$1.run(RoomTrackingLiveData.java:90)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 

6.+7.I will test it all after the sample is fixed again.

**Comment by jacobmichaelis** [comment]
That error is because I made some changes to the room schema. You will need to clear the data on the app on your phone or just delete the app.

As to the Samsung question, if I figure out a way to disable it, I will mention it in #6

**Comment by AndroidDeveloperLB** [comment]
About the error, this is odd. I uninstalled the app and re-installed it, and it seems the data came back.

Does the Play Store (or Android) keep the data even for apps that are in debug mode?

EDIT:  after clear-data, it doesn't work at all. Doesn't crash, but doesn't show the person. Have you changed branches again?

**Comment by farmerbb** [comment]
Regarding the app data coming back after a re-install, Android's data backup system works independently of the Play Store, and we have `android:allowBackup="true"` enabled in the manifest, so it's no surprise that the data was restored after a reinstall.

Regarding the crashes, @jacobmichaelis 's latest changes are working for me with a clean build of the `callerid` branch.  Did you make sure the contact was re-added inside the sample app after you cleared the app data?

**Comment by AndroidDeveloperLB** [comment]
App data comes back even for debug? Is it possible to disable it for debug?

As for the issue, again, I cloned just the default one. Currently it's "callerid". Should I have done differently?

I tried again, and now it works fine, including the photo too.
However, if I go to the recent calls and then enter the one that has called, I don't see the photo (but I do see the name I've set). Do you know why it's like that?

**Comment by farmerbb** [comment]
I've updated the manifest to set `android:allowBackup` to `false`.  Data backups aren't needed anyway for a sample app.

I'm still not seeing any crashes when building against the `callerid` branch.  (Yes, keep using that branch)

I'll defer to @jacobmichaelis to see if he has any ideas on getting the caller ID picture to persist in the user's recent calls.

**Comment by AndroidDeveloperLB** [comment]
@farmerbb Please ignore the error. He already explained about it. Now it works fine.

**Comment by AndroidDeveloperLB** [comment]
@jacobmichaelis 
OK I've performed some tests. Here are my answers to my questions, and new ones:

Edge case 3 (2 apps that offer this service) : very weird things occur when 2 apps offer data. The data is returned randomly. Not seem by the fast one or something. Sometimes I even saw just the text without the image.

1.The app will return the information just fine even if it takes time for it and the user answered.

2.I don't see a way to secure the ContentProvider in this case, and I don't see even a way for ContentProvider to know which app performed the query. I think the only protection you can do is to monitor the phone calls, and/or limit number of queries to once per minute or so...

5.I've noticed that for images, you chose to override `openAssetFile` . If you take it from the Internet, I think `openFile` is better, as it will probably allow you to download to a file first.

6.Adding Thread.sleep to the `openAssetFile` , I can see that indeed it could be possible. This means that the Phone app indeed shows the basic information and then asks for a photo (or it does both concurrently).

7.I've set it to min API 16.  Tried on API 16 and 19. Both didn't work with this sample project. So I tried API 21 instead. Still didn't work. I think it's all about the Phone app instead. Not the Android version. Should probably be available from Android 7 or 6. Which lowest Android version have you tested?

I suggest that after we close this thread, you will put some FAQ on the main page of this repository.

**Comment by jacobmichaelis** [comment]
I'd like to say I'm sorry for not responding but unfortunately the maintenance of this tutorial repo does not come through my workflow. For this reason I will be closing this thread and be unlikely to answer further questions. If I discover other issues with this project I will update the repo and the README and post on the StackOverflow questions I have been following regarding Caller ID Providers.
